### ISSUE TITLE
refreshing duplicates images on the plex side

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#13]
refreshing metadata re-downloads the two image types for each scene. if you do this a bunch you will end up with 10+ after a bit, this will can also cause it to clear the currently set image i believe where it sets itself to an image that does not exist which leaves the thumbnail empty.

**Comment by MikeLund** [comment]
> refreshing metadata re-downloads the two image types for each scene

To clarify, you mean that it redownloads one of each image type (one in Posters, and one in Background)? If so, I don't think there's any way around this in Plex Agents; PMS will always fetch the image URLs provided when doing a metadata refresh -- it even happens for the "normal" official agents in my experience.

If you mean that there's two images in both Poster and Background, that's most likely from [this commit](https://github.com/Darklyter/StashPlexAgent.bundle/commit/fd12f0c3cb781e9212bfcdc034977e01cfed86ac). Try removing the localmedia bit there, and newly added media shouldn't include that Plex-generated image (and media prior to this change _should_ be removed automatically during next metadata refresh+bundle cleanup, but no promises). I'm unsure why Darklyter made this change, because I see no tangible benefit from it, other than Plex will read in metadata from the file -- doesn't seem very important if you're wanting all your metadata to come from Stash anyways.

> if you do this a bunch you will end up with 10+ after a bit
> this will can also cause it to clear the currently set image i believe where it sets itself to an image that does not exist which leaves the thumbnail empty.

I can't reproduce either of these. Only way I have ended up with duplicate and/or multiple images is when I have manually added an image to a movie in Plex, at which case Plex adds a field `thumb.locked=1` in the media's XML. Check if that's the case, and if so, unlock it by using Plex's API `PUT /library/metadata/RATING_KEY?thumb.locked=0&X-Plex-Token=...`
